blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

myapp/urls.py
from django.urls import path
from .views import testview, articleaddview, articleshow, commentaddview, CommentList

urlpatterns = [
    path('', testview),
    path('article-add/', articleaddview),
    path('details/<int:id>', articleshow),
    path('add-comment/', commentaddview),
    path('view-comments/', CommentList.as_view())  #REST API URL
]

myapp/models.py
from django.db import models
from django_quill.fields import QuillField

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=124)
    author = models.CharField(max_length=36)
    publication_date = models.DateField()
    # body = models.TextField()
    body = QuillField(blank=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    title = models.CharField(max_length=64)
    author = models.CharField(max_length=36)
    publication_date = models.DateField(null=True)
    body = QuillField(blank=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

myapp/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = "__all__"
        widgets = {
            'publication_date': forms.DateInput(attrs={'type': 'date'})
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        # exclude = ['article']
        fields = ['title', 'author', 'body', 'article']
        # widgets = {
        #     'publication_date': forms.DateInput(attrs={'type': 'date'})
        # }

myapp/views.py
from django.shortcuts import render
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from .forms import ArticleForm, CommentForm
from .models import Article, Comment
from rest_framework.views import APIView
from .serializers import CommentSerializer
from rest_framework.renderers import JSONRenderer
from django.utils.six import BytesIO
from rest_framework.parsers import JSONParser
from rest_framework.response import Response
from datetime import datetime

# Create your views here.

def testview(request):
    articles = Article.objects.all()
    return render(request, 'index.html', {'articles':articles})

def articleaddview(request):
    if request.method == 'GET':
        article_form = ArticleForm()
        return render(request, 'addarticle.html', {'article_form': article_form.as_div()})

    else:
        data = request.POST
        article_form = ArticleForm(request.POST)
        if article_form.is_valid():
            article_form.cleaned_data
            article = Article()
            article.title = data['title']
            article.author = data['author']
            article.body = data['body']
            article.publication_date = datetime.today()
            article.save()
            return HttpResponseRedirect('/')
        else:
            raise Exception("Form is not valid!");
        # print(data)
        # article = Article()
        # article.title = data['title']
        # article.author = data['author']
        # article.body = data['body']
        # article.publication_date = data['publication_date']
        # article.save()


def articleshow(request, id=1):
    comment_form = CommentForm()
    article = Article.objects.get(id=id)
    comments = Comment.objects.filter(article=id)
    return render(request, 'show_details.html', {'article': article, 'comments': comments , 'comment_form': comment_form.as_div()})

def commentaddview(request):
    data = request.POST
    # print(data)
    comment = Comment()
    comment.article = Article.objects.get(id=data['article'])
    comment.title = data['title']
    comment.author = data['author']
    comment.body = data['body']
    comment.publication_date = data['publication_date']
    comment.save()
    return HttpResponseRedirect('/')

# REST API that fetches all comments, the author of the comments, and the article on which the comment is made
class CommentList(APIView):
    def get(self, request):
        comments = Comment.objects.all()
        serializer = CommentSerializer(comments, many=True)
        return Response(serializer.data)

templates/addarticle.html
{% include 'header.html' %}

{% block content %}

      <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title text-center">Post Your Article</h5>
                    <form class="row g-3 add-form" action="" method="post">
                        {% csrf_token %}
                        {{ article_form }}
                        <button type="submit" class="btn btn-primary post text-center">post</button>
                    </form>
                </div>
            </div>
        </div>
      </div>


    <script>
        $(".add-form div").addClass('col-12');
        $(".add-form label").addClass('form-label');
        $(".add-form input, .add-form textarea").addClass('form-control');
    </script>

{% endblock %}

templates/base.html
{% load static %}
{% include 'django_quill/media.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>

      <!-- Favicons -->
      <link href="{% static 'img/favicon.png' %}" rel="icon">

      <!-- Google Fonts -->
      <link href="https://fonts.gstatic.com" rel="preconnect">
      <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

      <!-- Vendor CSS Files -->
      <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <link href="{% static 'bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
      <link href="{% static 'boxicons/css/boxicons.min.css' %}" rel="stylesheet">
<!--      <link href="{% static 'quill/quill.snow.css' %}" rel="stylesheet">-->
<!--      <link href="{% static 'quill/quill.bubble.css' %}" rel="stylesheet">-->
      <link href="{% static 'remixicon/remixicon.css' %}" rel="stylesheet">
      <link href="{% static 'simple-datatables/style.css' %}" rel="stylesheet">

      <!-- Template Main CSS File -->
      <link href="{% static 'css/style.css' %}" rel="stylesheet">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
</head>
<body>
    {% block content %} {% endblock %}

  <script src="{% static 'apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'chart.js/chart.min.js' %}"></script>
  <script src="{% static 'echarts/echarts.min.js' %}"></script>
<!--  <script src="{% static 'quill/quill.min.js' %}"></script>-->
  <script src="{% static 'simple-datatables/simple-datatables.js' %}"></script>
  <script src="{% static 'tinymce/tinymce.min.js' %}"></script>
  <script src="{% static 'php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
<!--  <script src="{% static 'js/main.js' %}"></script>-->

</body>

</html>

templates/header.html
{% extends 'base.html' %}

{% block title %}BlogBook{% endblock %}

templates/index.html
{% include 'header.html' %}

{% block content %}



<div class="card">
    <div class="card-body">
        <div class="col-lg-6"> <h3 class="card-title">Articles</h3></div>
        <div class="row add-btn">
            <div class="col-lg-6">
                <a class="btn btn-primary float-right" href="article-add">Add New</a>
            </div>
        </div>


      <!-- Table with hoverable rows -->
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Title</th>
            <th scope="col">Published at</th>
          </tr>
        </thead>
        {% if articles %}
         {% for article in articles %}
            <tbody>
              <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="details/{{article.id}}">{{article.title}}</a></td>
                <td>{{article.publication_date | date:'c'}}</td>
              </tr>
            </tbody>
         {% endfor %}
        {% else %}
          <tbody>
            <tr>
                <td></td>
                <td align="center">No article found</td>
                <td></td>
            </tr>
          </tbody>
        {% endif %}

      </table>
      <!-- End Table with hoverable rows -->

    </div>
  </div>

{% endblock %}

templates/show_details.html
{% include 'header.html' %}

{% block content %}

<div class="row align-items-top">
    <div class="col-lg-12">
        <div class="card article-single" data-id="{{article.id}}">
        <div class="card-header text-left">
            <h4>{{article.title}}</h4>
            <p><small>by {{article.author}} on {{article.publication_date}}</small></p>
        </div>

        <div class="card-body">

                {% if article.body.html|safe|length > 500 %}
                    <div class="excerpt">
                            {{ article.body.html | safe | slice:":500" | add:" " }}
                            <a href="javascript:void(0);" class="more_info">more...</a>
                    </div>

                    <div class="details" style="display:none;">
                        {{ article.body.html | safe }}
                        <br><a href="javascript:void(0);" class="less_info">less...</a>
                    </div>
                {% else %}
                 <div class="">
                    {{ article.body.html | safe }}
                 </div>
                {% endif %}

            </div>



        </div>
        <div class="card-footer">

          <h5 class="card-title left">Comments:</h5>
            <div class="container">
                <form class="row g-3 comment-form form-inline" action="/add-comment/" method="post">
                    {% csrf_token %}
                    {{ comment_form }}
                    <button type="submit" class="btn btn-primary commnt text-center">comment</button>
                </form>
            </div>
            <br>
            <div class="card">
                <div class="card-body">
                  {% for comment in comments %}
                  <span class="card-title">{{comment.title}}</span><br>
                  <small>{{comment.author}} - {{comment.publication_date}}</small>
                    <div class="main_cont">
                    {% if comment.body.html|safe|length > 100 %}
                        <div class="comm_excerpt_{{comment.id}}">
                            {{comment.body.html | safe | slice:":100" | add:" "}}
                            <a href="javascript:void(0);" data-id="{{comment.id}}" class="comm_more">more...</a>
                        </div>

                        <div class="comm_details_{{comment.id}}" style="display:none;">
                            {{comment.body.html | safe}}
                            <a href="javascript:void(0);" data-id="{{comment.id}}" class="comm_less">less...</a>
                        </div>
                    {% else %}
                        <div>{{comment.body.html | safe}}</div>
                    {% endif %}
                    </div>
                  {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}



<!--{% load static %}-->
<!--<script type="text/javascript" src="{% static 'js/show_details.js' %}"></script>-->


<script>

$(".more_info").on("click", function() {
    $(".excerpt").hide();
    $(".details").show();
});
$(".less_info").on("click", function() {
    $(".details").hide();
    $(".excerpt").show();
});

$(".comm_more").on("click", function() {
    var id = $(this).data('id');
    $(".comm_excerpt_"+id).hide();
    $(".comm_details_"+id).show();
});
$(".comm_less").on("click", function() {
    var id = $(this).data('id');
    $(".comm_details_"+id).hide();
    $(".comm_excerpt_"+id).show();
});

$(document).ready(function() {
     let id = $(".article-single").data('id');
     $("#id_article option[value="+id+"]").prop("selected", true);
     $("#id_article").hide();
     $("#id_article").prev().hide();
     $("#id_publication_date").hide();
     $("#id_publication_date").prev().hide();
     $(".comment-form div").addClass('col-md-3');
     $(".comment-form .django-quill-widget-container, .comment-form .django-quill-widget-container div").removeClass('col-md-3').addClass('col-md-10');
     $(".comment-form .django-quill-widget-container").parent().removeClass('col-md-3').addClass('col-md-10');
     $(".comment-form label").addClass('form-label');
     $(".comment-form input, .comment-form textarea").addClass('form-control');
});





</script>

templates/show_detals.html
{% include 'header.html' %}

{% block content %}

    <div class="article-single" data-id="{{article.id}}">
        <h2>{{article.title}}</h2>
        <p><small>by {{article.author}} on {{article.publication_date}}</small></p>
        <br>
        <div class="excerpt">
            {{ article.body | slice:":20" | add:" " }}
            <a href="javascript:void(0);" class="more_info">more...</a>
        </div>
        <div class="details" style="display:none;">
            {{ article.body }}
            <br><a href="javascript:void(0);" class="less_info">less...</a>
        </div>
    </div>

{% endblock %}

<div class="comment-sec">
    <h3>Comments:</h3> <br>
    <form action="/myapp/add-comment/" method="post">
        {% csrf_token %}
<!--        <input type="hidden" name="article_id" value="{{ article.id }}">-->
        {{ comment_form }}
        <input type="submit" value="POST">
    </form>
    <br>

    <div>
        {% for comment in comments %}
        <div>
            <h4>{{comment.title}}</h4>
            <small>{{comment.author}} - {{comment.publication_date}}</small>
            <p>{{comment.body}}</p>
        </div>
        {% endfor %}
    </div>


</div>


<!--{% load static %}-->
<!--<script type="text/javascript" src="{% static 'js/show_details.js' %}"></script>-->

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>

<script>

$(".more_info").on("click", function() {
    $(".excerpt").hide();
    $(".details").show();
});
$(".less_info").on("click", function() {
    $(".details").hide();
    $(".excerpt").show();
});

$(document).ready(function() {
    let id = $(".article-single").data('id');
    console.log('id '+id);
    $("#id_article option[value="+id+"]").prop("selected", true);
    $("#id_article").hide();
});






</script>